import hashlib
from datetime import datetime

def build_test_header(prompt: str, module_name: str, model: str = "gpt-4o") -> str:
    date = datetime.utcnow().strftime("%Y-%m-%d")
    prompt_hash = hashlib.sha256(prompt.encode("utf-8")).hexdigest()[:12]

    header_lines = [
        "# =======================================",
        f"# Auto-generated by {model}",
        f"# Date: {date}",
        f"# Module: {module_name}",
        f"# Prompt SHA256: {prompt_hash}",
        "# =======================================",
        "",
    ]
    return "\n".join(header_lines)