name: Run Pytest and Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install test dependencies
        run: |
          pip install -r ingestion/requirements-dev.txt

      - name: Run tests with Pytest
        run: |
          PYTHONPATH=ingestion pytest ingestion/tests/ --maxfail=3 --disable-warnings -v

      - name: Check formatting with Black
        id: black_check
        continue-on-error: true
        run: |
          black --check ingestion/arkhamanalytics ingestion/tests
      
      - name: Auto-format with Black if needed
        if: steps.black_check.outcome == 'failure'
        run: |
          echo "Some files need formatting. Running Black to fix..."
          black ingestion/arkhamanalytics ingestion/tests

      - name: Lint with Flake8 (via pyproject.toml)
        run: |
          flake8 --config=pyproject.toml ingestion/arkhamanalytics ingestion/tests

