name: Run Pytest and Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install test dependencies
        run: |
          pip install -r ingestion/requirements-dev.txt
          pip install pytest-cov  # Ensure coverage is available

      - name: Run tests with coverage
        run: |
          PYTHONPATH=ingestion pytest \
            --cov=ingestion/arkhamanalytics \
            --cov-report=term \
            --cov-report=xml \
            ingestion/tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          name: codecov-pytest

      - name: Check formatting with Black
        id: black_check
        continue-on-error: true
        run: |
          black --check ingestion/arkhamanalytics ingestion/tests
          
      - name: Auto-format with Black if needed
        if: steps.black_check.outcome == 'failure'
        run: |
          echo "Some files need formatting. Running Black to fix..."
          black ingestion/arkhamanalytics ingestion/tests

      - name: Lint with Flake8
        run: |
          flake8 ingestion/arkhamanalytics ingestion/tests --config=.flake8
